### ISSUE TITLE
Need clarification regarding purpose of Injector::disposeBloc method

### ISSUE THREAD

**Issue by mkuzmentsov** [diefferson/flutter_bloc_inject#1]
The Injector class' method `dispose` looks like this:
```
  void disposeBloc(Bloc bloc) {
    _blocs.remove(bloc);
  }
```

The weird thing is that contract of `_blocs` property is `final Map<String, TypeBloc<Bloc>> _blocs = Map<String, TypeBloc<Bloc>>();`.

Should it actually remove the TypeBloc from this map? As of now, nothing is being removed since the key in the map is being generated with a following function:
```
  String _makeKey<T>(T type, [String key]) =>
      "${type.toString()}::${key == null ? "default" : key}";
```

**Comment by diefferson** [comment]
Hi @BattleBeaver I think that a Bloc should lives together this widget, if you need a class that have a different lifecycle of widget you can use normal injection.

**Comment by diefferson** [comment]
Because this I implemented auto-dispose on blocs injects, to cancel some asynchronous request in bloc, and clear memory.

**Comment by mkuzmentsov** [comment]
@diefferson Probably `_blocs.remove(bloc);` was supposed to perform this cleanup, but it never deletes blocs from `_blocs` map, since the key stored in the map and the key provided in `_blocs.remove` are different. They even seem to be of different types - map holds `String -> TypeBloc` pairs like `SomeBloc::Default -> TypeBloc`, but the key we're trying to delete here is of type `Bloc`.

**Comment by mkuzmentsov** [comment]
@diefferson thanks for merging https://github.com/diefferson/flutter_bloc_inject/pull/3, could you then submit a new version of a package to dartpub please?

Closing this.
