### ISSUE TITLE
Need clarification regarding the expected behavior on bloc's + widget's disposal

### ISSUE THREAD

**Issue by mkuzmentsov** [diefferson/flutter_bloc_inject#2]
This comes up in scope of #1 

We're building an app using flutter_bloc_inject lib. There are AppInjector, Bloc and a Widget declared respectively. When switching from one Widget to another it's being disposed as well as the related bloc. But when I get back to initial widget and attempt to modify the `sink` on bloc, I see `[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add new events after calling close`. This is because the BlocType is a singleton and even after dispose it's not being reconstructed. To solve this we manually recreate BehaviorSubject on one of the Bloc's methods if the BehaviorSubject::isClosed returns true.

I can of course provide the sample app, but if you get an idea what's going on - please let me know. I'd be glad to collaborate - we're pretty comfortable with this library. 

Thanks in advance.

**Comment by mkuzmentsov** [comment]
@diefferson please see the PR and let me know if there's anything I can change out there, to get it merged, thanks in advance

**Comment by diefferson** [comment]
Hi @BattleBeaver as I mentioned in another issue I guess that Blocs should to live with theirs widget, for this I implemented blocs auto-dispose. Do you had problems with this dispose? the bloc isn't created when the widget is restarted?

**Comment by mkuzmentsov** [comment]
@diefferson No, it's not created because of TypeBloc having contract like this:
```
class TypeBloc<T extends Bloc> {
  final BlocFactoryFnWithParamsFn<T> _factoryFn;

  T _instance;

  TypeBloc(this._factoryFn);

  T get(Injector injector, Map<String, dynamic> additionalParameters) {
    if (_instance == null) {
      _instance = _factoryFn(injector, additionalParameters);
    }

    return _instance;
  }
}
```
so it's a singleton, and each TypeBloc is stored in 
`final Map<String, TypeBloc<Bloc>> _blocs = Map<String, TypeBloc<Bloc>>();` and never get's removed from it. So each TypeBloc lives until app is running. Thus, when I implement `dispose()` in bloc and it gets called on widget disposal, the bloc still alive when widget is reopened (and it's the same instance) but Observables are closed, . 

It can be that I'm missing something, but it looks like the case.

**Comment by mkuzmentsov** [comment]
@diefferson ok, I think I will just write our own micro lib for this, thanks!

**Comment by diefferson** [comment]
Hi @BattleBeaver I have accepted your pull request, If you develop some lib that you consider nice to add in Flutter Block Inject, please feel free for send new suggestions, this lib is not mine is ours

**Comment by mkuzmentsov** [comment]
@diefferson roger, thank you! We're looking forward to see the new version deployed to dartpub!
